services:
  pinot:
    image: apachepinot/pinot:${PINOT_VERSION:-1.2.0}
    container_name: pinot
    working_dir: /opt/pinot
    volumes:
      - ./controller.conf:/opt/pinot/controller.conf:ro
      - ./broker.conf:/opt/pinot/broker.conf:ro
      - ./server.conf:/opt/pinot/server.conf:ro
      - ./minion.conf:/opt/pinot/minion.conf:ro
      - ./start-pinot.sh:/opt/pinot/start-pinot.sh
    entrypoint: "/opt/pinot/start-pinot.sh"
    ports:
      - "9000:9000"
      - "8099:8099"
      - "8098:8098"
      - "8097:8097"