version: "3.8"

services:
  fastjson-insecure:
    image: eclipse-temurin:8-jre
    container_name: fastjson-insecure
    volumes:
      - ./fastjson-playground-vuln.jar:/app.jar
    command: java -jar /app.jar
    ports:
      - "8081:8080"

  fastjson-secure:
    image: eclipse-temurin:8-jre
    container_name: fastjson-secure
    volumes:
      - ./fastjson-playground-safe.jar:/app.jar
    command: java -jar /app.jar
    ports:
      - "8082:8080"

