version: "3.8"

services:
  fastjson-vuln:
    build:
      context: .
      dockerfile: Dockerfile-vuln
    container_name: fastjson-vuln
    ports:
      - "8081:8080"

  fastjson-safe:
    build:
      context: .
      dockerfile: Dockerfile-safe
    container_name: fastjson-safe
    ports:
      - "8082:8080"


